server:
  port: 8080

logging:
  level:
    root: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: changeme

  flyway:
    user: postgres
    password: changeme