server:
  port: 8081

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: changeme

  flyway:
    user: postgres
    password: changeme