spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testru
    driver-class-name: org.h2.Driver

  flyway:
    user: sa
    password: ""

#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
